trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: compliance
  displayName: Compliance Analysis
  jobs:
  - job: projectAnalysis
    displayName: Project Analysis
    steps:
    - script: echo "Stage compliance"

- stage: build
  dependsOn: 
  - compliance
  displayName: Build
  jobs:
  - job: functionBuild
    displayName: Function Build
    steps:
    - script: echo "Stage build"

- stage: qualityAnalysis
  dependsOn: 
  - build
  displayName: Code Quality Analysis
  jobs:
  - job:
    displayName: SonarQube
    steps:
    - script: echo "Stage quality"

- stage: qualityGate
  dependsOn:
  - qualityAnalysis
  displayName: Quality Gate
  jobs:
  - job:
    displayName: Quality Gate
    steps:
    - script: echo "Stage qualityGate"

- stage: artifactsUpload
  dependsOn:
  - build
  - qualityGate
  displayName: Artifacts Upload
  jobs:
  - job: artifactsUploadJob
    displayName: Artifacts Upload
    steps:
    - script: echo "Stage artifactsUpload"

- stage: deploy
  dependsOn:
  - build
  - artifactsUpload
  displayName: Deploy
  jobs:
  - job: functionDeploy
    displayName: Function Deploy
    steps:
    - script: echo "Stage deploy"